# Generated by Django 6.0.4 on 2026-05-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=50, unique=True)),
                ('total_biaya_tindakan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_biaya_obat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_pembayaran', models.CharField(default='belum_lunas', max_length=20)),
                ('waktu_pembayaran', models.DateTimeField(blank=True, null=True)),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
    ]
