# Generated by Django 6.0.4 on 2026-05-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keuangan', '0001_initial'),
        ('master_data', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihan',
            name='kunjungan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.kunjungan'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='metode_bayar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.metodepembayaran'),
        ),
    ]
