# Generated by Django 6.0.4 on 2026-05-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmasi', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='rekam_medis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.rekammedis'),
        ),
        migrations.AddField(
            model_name='detailresep',
            name='resep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.resep'),
        ),
    ]
